### ISSUE TITLE
A console warning is observed regarding a referenced image asset

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/WordPressAuthenticator-iOS#38]
When using a `WordPressAuthenticator` component in WordPress-iOS, I'm seeing the following warning in the console:
```
2018-12-11 09:21:31.650079-0800 WordPress[91387:1155878] Could not load the "beveled-blue-button-down" image referenced from a nib in the bundle with identifier "org.cocoapods.WordPressAuthenticator"
```

**Comment by stevebaranski** [comment]
I'm afraid that this is still an issue in/on WPiOS. I am able to reproduce when attempting to login; navigating to the below screen evinces the aforementioned console log entry.
<img width="584" alt="wpa-38" src="https://user-images.githubusercontent.com/221062/55815854-ec2d3480-5aa5-11e9-9120-4eed26be7bd7.png">

I believe the image is missing from `WordPressAuthenticator`. I see it referenced in [this storyboard](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/d665345e2b13181391e8399274db14d9680d2c20/WordPressAuthenticator/NUX/NUXButtonView.storyboard#L111), but I don't see it within the module.

It appears that this image is located within WPiOS itself, referenced in both [`AppImages.xcassets`](https://github.com/wordpress-mobile/WordPress-iOS/tree/4ac54edd8c4db2978a0122f97e137c755e627d4a/WordPress/Resources/AppImages.xcassets/beveled-blue-button-down.imageset) and in [`LoginEpilogue.storyboard`](https://github.com/wordpress-mobile/WordPress-iOS/blob/4ac54edd8c4db2978a0122f97e137c755e627d4a/WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard#L187).

If I recall, `WordPressAuthenticator` was extracted into a standalone framework from WPiOS. Perhaps this image just wasn't ported at that time? 

Given that it's still used in WPiOS, perhaps the simplest solution is to copy it from the WPiOS asset catalog to [this one](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/tree/develop/WordPressAuthenticator/Resources/Assets.xcassets) in this framework?

**Comment by jtreanor** [comment]
Thanks for re-opening @stevebaranski!

After looking a little closer, it looks like that while `beveled-blue-button-down` is referenced from `NUXButtonView.storyboard`, it is not actually used in practice as the backgrounds are [generated in code](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/develop/WordPressAuthenticator/NUX/NUXButton.swift#L96).

I think this warning surfaced recently due to my changes to how resources are loaded in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/67. Thankfully it seems the warning was just that and has no other consequences.

I have opened a PR to remove references to `beveled-blue-button-down` here: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/77
