### ISSUE TITLE
UL&S: Add visual blur to Prologue button view

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPressAuthenticator-iOS#401]
Use a `UIVisualEffectView` with `.systemChrome` style for iOS 13+ and `regular` for iOS 12. This keeps our button view designs in line with other areas. For example, it's used in the "What's New" feature:

| Light | Dark |
| --- | --- |
| <a href="https://user-images.githubusercontent.com/1062444/91084721-0f607180-e612-11ea-9cfe-8eb2c19d6440.png"><img src="https://user-images.githubusercontent.com/1062444/91084721-0f607180-e612-11ea-9cfe-8eb2c19d6440.png" width="350" /></a> | <a href="https://user-images.githubusercontent.com/1062444/91084752-1a1b0680-e612-11ea-86f1-34de0d08c652.png"><img src="https://user-images.githubusercontent.com/1062444/91084752-1a1b0680-e612-11ea-86f1-34de0d08c652.png" width="350" /></a> |

**Comment by ScoutHarris** [comment]
@mattmiklic @mindgraffiti I'm a bit confused as to what this will accomplish. On the Prologue, the carousel pages sit on top of the button view, never going under. The [new designs](https://wpmobilep2.wordpress.com/2020/09/22/prologue_final_final_done_v5/) appear to be the same way. The blur made sense on the [Login Epilogue](https://github.com/wordpress-mobile/WordPress-iOS/pull/14979) since My Sites can scroll, thus achieving a blur. But here, there won't be anything to blur. 

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-24 at 11 23 05](https://user-images.githubusercontent.com/1816888/94178474-5da6a180-fe58-11ea-9e9d-71c2a38e5429.png)

**Comment by mindgraffiti** [comment]
@ScoutHarris oh that's true. Even the i5 prologue designs don't include a visual blur. @mattmiklic I propose closing this issue, unless there is an i6 for prologue designs expected that would incorporate a visual blur.

![i5-ios-1](https://user-images.githubusercontent.com/1062444/94186247-10ccc600-fe6c-11ea-9617-67a1afdf9341.png)

**Comment by mattmiklic** [comment]
My expectation for the prologue was that the background color would continue behind the button view, and the button view's system material would allow a bit of the color to show through. In @osullivanchris's latest prologue work the circular background pattern could continue underneath the system material too. It would be a quite subtle effect but I think the value in it would be matching the general background color and border style of the Epilogue and What's New button views; this would be the only screen that didn't use it if it weren't updated, I believe.

**Comment by osullivanchris** [comment]
Yeah that's what I was thinking too, that the background and pattern would continue to the bottom of the screen, but behind the buttons & blurry background

**Comment by ScoutHarris** [comment]
Ah, I see. Thanks @mattmiklic & @osullivanchris . Blur shall be added!
